version: '3.8'

services:
  sensorstats:
    build: .
    ports:
      - "${USER_PORT:-5006}:8080"
    environment:
      - PORT=8080
      - TZ=Europe/Madrid
    restart: unless-stopped
    volumes:
      - ./data:/app/data/historialDatos